In [50]:
# construct an adjacency matrix with the use of mdf created in the previous work 'prepareDfs_4'
import pandas as pd
mdf = pd.read_csv('mdf.csv')
print("mdf :\n", mdf.head())

mdf :
   출발영업소명 출발영업소주소 도착영업소명 도착영업소주소  도착지방향평균
0     서울     경기도     지곡     함양군    17.75
1     서울     경기도     양산     양산시     0.75
2     서울     경기도     군북     함안군     0.75
3     서울     경기도     장지     함안군     0.75
4     서울     경기도     함안     함안군     4.50

In [74]:
# get a node list from mdf['출발영업소주소']
nList = mdf['출발영업소주소'].unique()
print(len(nList))
print(nList)

# the last element concerns '두물머리' station which has not established yet
# figures concerning this will be removed after filling up the matrix first

29
['경기도' '함양군' '충청남도' '충청북도' '대전광역시' '경상북도' '대구광역시' '울산광역시' '양산시' '부산광역시'
 '함안군' '창원시' '김해시' '전라북도' '전라남도' '강원도' '산청군' '진주시' '창녕군' '합천군' '광주광역시'
 '거창군' '하동군' '사천시' '고성군' '통영시' '세종특별자치시' '밀양시' '예정']

In [75]:
# create an empty matrix to fill up
adjMatrix = pd.DataFrame(np.zeros((len(nList),len(nList))), columns=nList, index=nList)
adjMatrix.head()

,경기도,함양군,충청남도,충청북도,대전광역시,경상북도,대구광역시,울산광역시,양산시,부산광역시,...,합천군,광주광역시,거창군,하동군,사천시,고성군,통영시,세종특별자치시,밀양시,예정
경기도,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
함양군,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
충청남도,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
충청북도,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
대전광역시,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
# while iterating over the rows, fill up the elements
for index, row in mdf.iterrows():
    adjMatrix[row['출발영업소주소']][row['도착영업소주소']] += row['도착지방향평균']

adjMatrix.head()

C:\Users\syj43\AppData\Local\Temp\ipykernel_13412\1896738813.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  adjMatrix[row['출발영업소주소']][row['도착영업소주소']] += row['도착지방향평균']

,경기도,함양군,충청남도,충청북도,대전광역시,경상북도,대구광역시,울산광역시,양산시,부산광역시,...,합천군,광주광역시,거창군,하동군,사천시,고성군,통영시,세종특별자치시,밀양시,예정
경기도,0.00,461.50,0.00,0.00,0.0,0.00,0.0,0.00,58.75,0.0,...,18.75,0.0,101.25,74.5,420.00,155.00,841.75,0.0,10.25,0.0
함양군,419.75,595.75,195.75,91.75,254.5,178.25,329.0,22.75,13.75,117.0,...,16.50,143.0,272.75,23.0,118.75,28.00,92.00,27.5,0.00,0.0
충청남도,0.00,176.25,0.00,0.00,0.0,0.00,0.0,0.00,27.75,0.0,...,3.50,0.0,36.50,139.0,160.50,49.00,292.00,0.0,1.75,0.0
충청북도,0.00,102.50,0.00,0.00,0.0,0.00,0.0,0.00,15.75,0.0,...,11.25,0.0,36.25,54.0,122.00,35.75,190.25,0.0,0.50,0.0
대전광역시,0.00,233.25,0.00,0.00,0.0,0.00,0.0,0.00,14.75,0.0,...,3.25,0.0,35.25,55.0,216.00,60.75,354.25,0.0,0.25,0.0

In [77]:
# check out '예정'; sure there is no data related with a station not running right now!
adjMatrix['예정']

경기도        0.00
함양군        0.00
충청남도       0.00
충청북도       0.00
대전광역시      0.00
경상북도       0.00
대구광역시      0.00
울산광역시      0.00
양산시        0.00
부산광역시      0.00
함안군        0.75
창원시        0.25
김해시        0.75
전라북도       0.00
전라남도       0.00
강원도        0.00
산청군        0.00
진주시        0.00
창녕군        0.25
합천군        0.00
광주광역시      0.00
거창군        0.00
하동군        0.25
사천시        0.00
고성군        0.00
통영시        0.00
세종특별자치시    0.00
밀양시        0.00
예정         0.00
Name: 예정, dtype: float64

In [78]:
# drop concerning row and column, respectively
adjMatrix = adjMatrix.drop(['예정'], axis=0)
adjMatrix = adjMatrix.drop(['예정'], axis=1)

In [83]:
# save the adjMatrix in csv format for later use
adjMatrix.to_csv('adjMatrix.csv', index=True, encoding='utf-8')

In [ ]:
# end of code